--- SOAPdenovo2-src-r240/Makefile	2013-07-08 21:00:24.000000000 -0700
+++ patch-files/Makefile	2014-04-01 07:28:08.136477492 -0700
@@ -1,8 +1,8 @@
-CC = g++
+CC = icc
 ifdef debug
 CFLAGS=         -O0 -g -fomit-frame-pointer
 else
-CFLAGS=         -O4 -fomit-frame-pointer
+CFLAGS=         -O4 -fomit-frame-pointer
 endif
 
 SUBDIRS = sparsePregraph standardPregraph
