--- Makefile	2015-06-19 21:17:12.000000000 -0700
+++ patch-files/Makefile	2015-06-19 21:17:49.000000000 -0700
@@ -1,4 +1,4 @@
-CC = g++
+CXX = g++
 ifdef debug
 CFLAGS=         -O0 -g -fomit-frame-pointer
 else
@@ -51,11 +51,11 @@
 SOAPdenovo-63mer:
 	@cd sparsePregraph;make 63mer=1 debug=1;cd ..;
 	@cd standardPregraph;make 63mer=1 debug=1;cd ..;
-	@$(CC) sparsePregraph/*.o standardPregraph/*.o $(LIBPATH) $(LIBS) $(EXTRA_FLAGS) -o SOAPdenovo-63mer
+	@$(CXX) sparsePregraph/*.o standardPregraph/*.o $(LIBPATH) $(LIBS) $(EXTRA_FLAGS) -o SOAPdenovo-63mer
 SOAPdenovo-127mer:
 	@cd sparsePregraph;make 127mer=1 debug=1;cd ..;
 	@cd standardPregraph;make 127mer=1 debug=1;cd ..;
-	@$(CC) sparsePregraph/*.o standardPregraph/*.o $(LIBPATH) $(LIBS) $(EXTRA_FLAGS) -o SOAPdenovo-127mer
+	@$(CXX) sparsePregraph/*.o standardPregraph/*.o $(LIBPATH) $(LIBS) $(EXTRA_FLAGS) -o SOAPdenovo-127mer
 clean:
 	@cd sparsePregraph;make clean;cd ..;
 	@cd standardPregraph;make clean;cd ..;
@@ -64,11 +64,11 @@
 SOAPdenovo-63mer:
 	@cd sparsePregraph;make 63mer=1;cd ..;
 	@cd standardPregraph;make 63mer=1;cd ..;
-	@$(CC) sparsePregraph/*.o standardPregraph/*.o $(LIBPATH) $(LIBS) $(EXTRA_FLAGS) -o SOAPdenovo-63mer
+	@$(CXX) sparsePregraph/*.o standardPregraph/*.o $(LIBPATH) $(LIBS) $(EXTRA_FLAGS) -o SOAPdenovo-63mer
 SOAPdenovo-127mer:
 	@cd sparsePregraph;make 127mer=1;cd ..;
 	@cd standardPregraph;make 127mer=1;cd ..;
-	@$(CC) sparsePregraph/*.o standardPregraph/*.o $(LIBPATH) $(LIBS) $(EXTRA_FLAGS) -o SOAPdenovo-127mer
+	@$(CXX) sparsePregraph/*.o standardPregraph/*.o $(LIBPATH) $(LIBS) $(EXTRA_FLAGS) -o SOAPdenovo-127mer
 clean:
 	@cd sparsePregraph;make clean;cd ..;
 	@cd standardPregraph;make clean;cd ..;
