ifndef ROLLCOMPILER
  ROLLCOMPILER = gnu
endif
COMPILERNAME := $(firstword $(subst /, ,$(ROLLCOMPILER)))

NAME           = sdsc-tophat
VERSION        = 2.1.0
RELEASE        = 0
PKGROOT        = /opt/biotools/tophat

SRC_SUBDIR     = tophat

SOURCE_NAME    = tophat
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

OLDSAM_NAME    = samtools
OLDSAM_SUFFIX  = tar.bz2
OLDSAM_VERSION = 0.1.19
OLDSAM_PKG     = $(OLDSAM_NAME)-$(OLDSAM_VERSION).$(OLDSAM_SUFFIX)
OLDSAM_DIR     = $(OLDSAM_PKG:%.$(OLDSAM_SUFFIX)=%)

TAR_GZ_PKGS    = $(SOURCE_PKG)
TAR_BZ2_PKGS   = $(OLDSAM_PKG)

RPM.EXTRAS     = AutoReq:No
