NAME           = sdsc-SOAPsnp
VERSION        = v1.03
RELEASE        = 16
PKGROOT        = /opt/biotools/SOAPsnp

SRC_SUBDIR     = SOAPsnp

SOURCE_NAME    = SOAPsnp
SOURCE_SUFFIX  = tar.gz
SOURCE_VERSION = $(VERSION)
SOURCE_PKG     = $(SOURCE_NAME)-$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR     = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

TAR_GZ_PKGS    = $(SOURCE_PKG)

RPM.EXTRAS     = AutoReq:No
