--- vcftools_0.1.12b/Makefile	2014-08-01 12:11:22.000000000 -0700
+++ patch-files/Makefile	2015-06-05 11:27:13.399098733 -0700
@@ -17,7 +17,7 @@
 
 
 ifndef PREFIX
-    export PREFIX = $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
+    export PREFIX = $(PWD)
 endif
 export BINDIR = ${PREFIX}/bin
 export MANDIR = ${PREFIX}/bin/man1
@@ -27,7 +27,7 @@
 install:
 	    @mkdir -p $(BINDIR); mkdir -p $(MODDIR); mkdir -p $(MANDIR); \
 	    cp ${PREFIX}/cpp/vcftools.1 $(MANDIR); \
-        for dir in $(DIRS); do cd $$dir && $(MAKE) $(MAKEFLAGS) && cd ..; done
+        for dir in $(DIRS); do cd $$dir && $(MAKE) && cd ..; done
 
 clean:
 		@for dir in $(DIRS); do cd $$dir && $(MAKE) clean && cd ..; done
