--- Makefile	2014-10-11 07:46:39.651986976 -0700
+++ patch-files/Makefile	2014-10-11 07:54:07.816119547 -0700
@@ -21,7 +21,7 @@
 inchworm_target:
 	@echo Using $(TRINITY_COMPILER) compiler for Inchworm and Chrysalis
 	cd Inchworm && (test -e configure || autoreconf) \
-                && ./configure --prefix=`pwd` $(INCHWORM_CONFIGURE_FLAGS) && $(MAKE) install
+                && ./configure --prefix=ROLLPREFIX $(INCHWORM_CONFIGURE_FLAGS) && $(MAKE) install
 
 chrysalis_target:
 	cd Chrysalis && $(MAKE) UNSUPPORTED=yes $(CHRYSALIS_MAKE_FLAGS)
