#%Module1.0

set biotoolsHome /opt/biotools

set packageHome $biotoolsHome/blat
setenv BLATHOME $packageHome
prepend-path PATH $packageHome/bin/x86_64

set packageHome $biotoolsHome/bowtie
setenv BOWTIEHOME $packageHome
prepend-path PATH $packageHome/bin
prepend-path PATH $packageHome/scripts

set packageHome $biotoolsHome/bowtie2
setenv BOWTIE2HOME $packageHome
prepend-path PATH $packageHome/bin
prepend-path PATH $packageHome/scripts

set packageHome $biotoolsHome/bwa
setenv BWAHOME $packageHome
prepend-path PATH $packageHome/bin

set packageHome $biotoolsHome/GenomeAnalysisTK
setenv GATKHOME $packageHome
prepend-path CLASSPATH $packageHome

set packageHome $biotoolsHome/samtools
setenv SAMTOOLSHOME $packageHome
prepend-path PATH $packageHome/bin

set packageHome $biotoolsHome/velvet
prepend-path PATH $packageHome/bin
setenv VELVETHOME $packageHome

set packageHome $biotoolsHome/soapdenovo
prepend-path PATH $packageHome/bin
setenv SOAPDENOVOHOME $packageHome

set packageHome $biotoolsHome/cufflinks
prepend-path PATH $packageHome/bin
prepend-path LD_LIBRARY_PATH /opt/boost/gnu/lib
setenv CUFFLINKSHOME $packageHome

set packageHome $biotoolsHome/gmap_gsnap
prepend-path PATH $packageHome/bin
setenv GMAP_GSNAPHOME $packageHome

set packageHome $biotoolsHome/tophat
prepend-path PATH $packageHome/bin
prepend-path LD_LIBRARY_PATH /opt/boost/gnu/lib
setenv TOPHATHOME $packageHome

set packageHome $biotoolsHome/fastx
setenv FASTXHOME $packageHome
prepend-path PATH $packageHome/bin
prepend-path LD_LIBRARY_PATH $packageHome/lib

set packageHome $biotoolsHome/fastqc
setenv FASTQCHOME $packageHome
prepend-path PATH $packageHome

set packageHome $biotoolsHome/cufflinks
setenv CUFFLINKSHOME $packageHome
prepend-path PATH $packageHome/bin

set packageHome $biotoolsHome/trinity
setenv TRINITYHOME $packageHome
prepend-path PATH $packageHome/bin:$packageHome

set packageHome $biotoolsHome/SOAPsnp
setenv SOAPSNPHOME $packageHome
prepend-path PATH $packageHome/bin

set packageHome $biotoolsHome/picard
setenv PICARDHOME $packageHome
prepend-path CLASSPATH $packageHome
prepend-path CLASSPATH $packageHome/picard-tools

set packageHome $biotoolsHome/spades
setenv SPADESHOME $packageHome
prepend-path PATH $packageHome/bin

set packageHome $biotoolsHome/biopython
setenv BIOPYTHONHOME $packageHome
prepend-path PYTHONPATH $packageHome/lib/pythonPYV/site-packages

set packageHome $biotoolsHome/dendropy
setenv DENDROPYHOME $packageHome
prepend-path PYTHONPATH $packageHome/lib/pythonPYV/site-packages

set packageHome $biotoolsHome/plink
setenv PLINKHOME $packageHome
prepend-path PATH $packageHome/bin

set packageHome $biotoolsHome/bismark
setenv BISMARKHOME $packageHome
prepend-path PATH $packageHome

set packageHome $biotoolsHome/htseq
setenv HTSEQHOME $packageHome
prepend-path PYTHONPATH $packageHome/lib/python2.7/site-packages

set packageHome $biotoolsHome/rnastar
setenv RNASTARHOME $packageHome
prepend-path PATH $packageHome/bin

set packageHome $biotoolsHome/trimmomatic
setenv TRIMMOMATICHOME $packageHome
prepend-path CLASSPATH $packageHome/trimmomatic-0.32.jar
 
set packageHome $biotoolsHome/blast
setenv BLASTHOME $packageHome
prepend-path PATH $packageHome/bin

set packageHome $biotoolsHome/bamtools
setenv BAMTOOLSHOME $packageHome
prepend-path PATH $packageHome/bin
prepend-path LD_LIBRARY_PATH $packageHome/lib/bamtools
