--- randfold-2.0/Makefile	2005-04-06 00:59:02.000000000 -0700
+++ patch-files/Makefile	2014-05-06 19:13:15.401926477 -0700
@@ -1,6 +1,6 @@
 CC=gcc
-LIBS=-lm -lsquid 
-INCLUDE=-I. 
+LIBS=-LROLLSQUID/lib -lm -lsquid 
+INCLUDE=-I. -IROLLSQUID/include
 CFLAGS=-O3
 
 randfold: energy_par.o params.o fold.o fold_vars.o utils.o randfold.c
