NAME              = sdsc-trinity
VERSION           = 2.8.4
RELEASE           = 1
PKGROOT           = /opt/biotools/trinity

SRC_SUBDIR        = trinity

SOURCE_NAME       = trinityrnaseq-Trinity
SOURCE_SUFFIX     = tar.gz
SOURCE_VERSION    = 2.8.4
SOURCE_PKG        = $(SOURCE_NAME)-v$(SOURCE_VERSION).$(SOURCE_SUFFIX)
SOURCE_DIR        = $(SOURCE_PKG:%.$(SOURCE_SUFFIX)=%)

JELLYFISH_NAME    = jellyfish
JELLYFISH_SUFFIX  = tar.gz
JELLYFISH_VERSION = 2.2.10
JELLYFISH_PKG     = $(JELLYFISH_NAME)-$(JELLYFISH_VERSION).$(JELLYFISH_SUFFIX)
JELLYFISH_DIR     = $(JELLYFISH_PKG:%.$(JELLYFISH_SUFFIX)=%)

SALMON_NAME    = salmon
SALMON_SUFFIX  = tar.gz
SALMON_VERSION = 0.12.0-alpha
SALMON_PKG     = $(SALMON_NAME)-$(SALMON_VERSION).$(SALMON_SUFFIX)
SALMON_DIR     = $(SALMON_PKG:%.$(SALMON_SUFFIX)=%)

TAR_GZ_PKGS       = $(SOURCE_PKG) $(JELLYFISH_PKG) $(SALMON_PKG)

RPM.EXTRAS        = AutoReq:No\nAutoProv:No
RPM.PREFIX        = $(PKGROOT)
