#%Module1.0

set biotoolsHome /opt/biotools

module-whatis "miso 0.5.3"

module load gnu python scipy

set packageHome /opt/biotools/miso
setenv MISOHOME $packageHome
append-path PATH $packageHome/bin
set lib [glob -nocomplain $packageHome/lib*/python*/site-packages]
append-path PYTHONPATH $lib

set packageHome /opt/biotools/samtools
setenv SAMTOOLSHOME $packageHome
append-path PATH $packageHome/bin
