#%Module1.0

set biotoolsHome /opt/biotools

module-whatis "miso VERSION"

module load python scipy

set packageHome /opt/biotools/miso
setenv MISOHOME $packageHome
append-path PATH $packageHome/bin
set lib [glob -nocomplain $packageHome/lib*/python*/site-packages]
append-path PYTHONPATH $lib

set packageHome /opt/biotools/samtools
setenv SAMTOOLSHOME $packageHome
append-path PATH $packageHome/bin


set packageHome /opt/biotools/pysam
setenv PYSAMHOME $packageHome
append-path PATH $packageHome/bin
set lib [glob -nocomplain $packageHome/lib*/python*/site-packages]
append-path PYTHONPATH $lib
