--- bcftools-1.3/Makefile	2015-12-15 13:58:35.000000000 -0800
+++ patch-files/Makefile	2015-12-22 16:20:30.272103694 -0800
@@ -37,7 +37,7 @@
 
 CC       = gcc
 CPPFLAGS =
-CFLAGS   = -g -Wall -Wc++-compat -O2
+CFLAGS   = -g -Wall -Wc++-compat -O2 -I$(GSLHOME)/include
 LDFLAGS  =
 LIBS     =
 
@@ -57,7 +57,7 @@
 ifdef USE_GPL
     EXTRA_CPPFLAGS += -DUSE_GPL
     OBJS += polysomy.o peakfit.o
-    GSL_LIBS = -lgsl -lcblas
+    GSL_LIBS = -L$(GSLHOME)/lib -lgsl -lgslcblas
 endif
 
 prefix      = /usr/local
