--- bcftools-1.9/Makefile	2018-07-18 02:05:19.000000000 -0700
+++ patch-files/Makefile	2018-10-08 18:12:52.935223303 -0700
@@ -131,7 +131,7 @@
 ifdef USE_GPL
     main.o : EXTRA_CPPFLAGS += -DUSE_GPL
     OBJS += polysomy.o peakfit.o
-    GSL_LIBS ?= -lgsl -lcblas
+    GSL_LIBS = -L$(GSLHOME)/lib -lgsl -lgslcblas
 endif
 
 bcftools: $(OBJS) $(HTSLIB)
